steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -n "$_BASE_BRANCH" ]; then
        BRANCH=$_BASE_BRANCH
      else
        BRANCH=$BRANCH_NAME
      fi
      case $BRANCH in
        "dev")
          terraform workspace select dev
          terraform init
        ;;
        "main")
          terraform workspace select prod
          terraform init
        ;;
        *)
        ;;
      esac

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [ -n "$_BASE_BRANCH" ]; then
        BRANCH=$_BASE_BRANCH
      else
        BRANCH=$BRANCH_NAME
      fi
      case $BRANCH in
        "dev")
          terraform workspace select dev
          terraform plan -out=/workspace/tfplan -input=false
        ;;
        "main")
          terraform workspace select prod
          terraform plan -out=/workspace/tfplan -input=false
        ;;
        *)
        ;;
      esac 
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [[ "$BRANCH_NAME" == main ]] || [[ "$BRANCH_NAME" == dev ]]; then 
        case $BRANCH_NAME in
          "dev")
            terraform workspace select dev
            terraform apply -input=false /workspace/tfplan
          ;;
          "main")
            terraform workspace select prod
            terraform apply -input=false /workspace/tfplan
          ;;
          *)
          ;;
        esac
      else
        echo "Branch is not main or dev. No action taken."
      fi
