steps:
- id: 'tf init'
  name: 'hashicorp/terraform:1.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - |
      if [[ -n $_BASE_BRANCH ]]; then
        echo "Not a PR merging to dev or main branch. Skipping."
      else
        case $BRANCH_NAME in
          "dev")
            terraform workspace select dev
            terraform init
          ;;
          "main")
            terraform workspace select prod
            terraform init
          ;;
          *)
          ;;
        esac
      fi
      

# [START tf-plan]
- id: 'tf plan'
  name: 'hashicorp/terraform:1.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [[ -n $_BASE_BRANCH ]]; then
        echo "Not a PR merging to dev or main branch. Skipping."
      else
        case $BRANCH_NAME in
          "dev")
            terraform workspace select dev
            terraform plan -out=/workspace/tfplan -input=false
          ;;
          "main")
            terraform workspace select prod
            terraform plan -out=/workspace/tfplan -input=false
          ;;
          *)
          ;;
        esac     
      fi
# [END tf-plan]

# [START tf-apply]
- id: 'tf apply'
  name: 'hashicorp/terraform:1.5'
  entrypoint: 'sh'
  args: 
  - '-c'
  - | 
      if [[ $BRANCH_NAME == "main" ]]; then 
        terraform workspace select prod
        terraform apply -input=false /workspace/tfplan
      else
        echo "Branch is not main. No action taken."
      fi
# [END tf-apply]      